spring:
  application:
    name: selfblog
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev} # Default to 'dev' if not specified
  jackson:
    time-zone: UTC
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    baseline-on-migrate: true
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

jwt:
  expiration:
    access: 86400000 # 24 hours (in milliseconds)
    refresh: 604800000 # 7 days (in milliseconds)

server:
  port: ${PORT:8080} # Render uses PORT environment variable
  tomcat:
    uri-encoding: UTF-8
